using UnityEngine;
using UnityEngine.AI;
using System.Collections;
using System.Collections.Generic;

/// <summary>
/// Kamatayan animation states corresponding to available animations
/// </summary>
public enum KamatayanAnimationState
{
    Idle,           // Standing idle
    Patrolling,     // Walking/roaming around
    Looking,        // Stopped and looking for player
    Chasing,        // Following the detected player
    Attacking       // Performing attack (if needed later)
}

/// <summary>
/// Kamatayan AI Controller:
/// - Patrols around the map using waypoints
/// - Periodically stops to look for the player from current position
/// - Follows the player when detected within detection range
/// - Can be configured with custom patrol routes and detection parameters
///
/// Setup:
/// - Add this component to the Kamatayan GameObject
/// - Add/assign a NavMeshAgent to the Kamatayan
/// - Set up patrol waypoints in the scene or use auto-generated patrol
/// - Assign the Player (or leave null to auto-find by tag "Player")
/// - Configure detection and behavior parameters
/// </summary>
public class KamatayanController : MonoBehaviour
{
    [Header("References")]
    [SerializeField] Transform player;
    [SerializeField] NavMeshAgent navMeshAgent;
    [SerializeField] Animator animator; // optional

    [Header("Patrol Behavior")]
    [SerializeField] Transform[] patrolWaypoints;
    [SerializeField] float waitTimeAtWaypoint = 2f;
    [SerializeField] float patrolSpeed = 3.5f;
    [SerializeField] bool useRandomPatrol = false;
    [SerializeField, Tooltip("If no waypoints are set, generates random patrol points within this radius")]
    float autoPatrolRadius = 20f;

    [Header("Detection & Looking Behavior")]
    [SerializeField] float detectionRadius = 15f;
    [SerializeField] float lookingInterval = 5f; // How often to stop and look around
    [SerializeField] float lookingDuration = 3f; // How long to look around
    [SerializeField] bool requireLineOfSight = true;
    [SerializeField] LayerMask lineOfSightObstructionMask = ~0;
    [SerializeField] float rotationSpeed = 2f;
    [SerializeField, Tooltip("Field of view angle for player detection when looking")]
    float fieldOfViewAngle = 60f;

    [Header("Chase Behavior")]
    [SerializeField] float chaseSpeed = 6f;
    [SerializeField] float loseChaseDistance = 25f;
    [SerializeField] float chaseTimeout = 30f; // Stop chasing after this time if player not found
    [SerializeField, Tooltip("Once detected, continue chasing even if LOS is lost")]
    bool persistentChase = true;

    [Header("Animation Parameters")]
    [SerializeField] string animParamIsIdle = "IsIdle";
    [SerializeField] string animParamIsWalking = "IsWalking";
    [SerializeField] string animParamIsLooking = "IsLooking";
    [SerializeField] string animParamIsChasing = "IsChasing";

    // Private variables
    private KamatayanAnimationState currentState = KamatayanAnimationState.Idle;
    private int currentWaypointIndex = 0;
    private bool isPlayerDetected = false;
    private bool isLooking = false;
    private bool isChasing = false;
    private float lastLookTime;
    private float chaseStartTime;
    private Vector3 lastKnownPlayerPosition;
    private List<Vector3> autoGeneratedWaypoints = new List<Vector3>();

    void Reset()
    {
        navMeshAgent = GetComponent<NavMeshAgent>();
    }

    void Awake()
    {
        if (navMeshAgent == null)
            navMeshAgent = GetComponent<NavMeshAgent>();
    }

    void Start()
    {
        // Auto-find player if not assigned
        if (player == null)
        {
            GameObject playerObj = GameObject.FindGameObjectWithTag("Player");
            if (playerObj != null)
                player = playerObj.transform;
        }

        // Initialize patrol system
        InitializePatrolSystem();
        
        // Set initial navigation speed
        navMeshAgent.speed = patrolSpeed;
        
        // Start patrolling
        SetState(KamatayanAnimationState.Patrolling);
        StartPatrolling();

        Debug.Log($"[{name}] Kamatayan Controller initialized. Player: {(player != null ? player.name : "Not Found")}");
    }

    void InitializePatrolSystem()
    {
        // If no waypoints are manually set, generate some automatically
        if (patrolWaypoints == null || patrolWaypoints.Length == 0)
        {
            GenerateAutoPatrolWaypoints();
        }
    }

    void GenerateAutoPatrolWaypoints()
    {
        autoGeneratedWaypoints.Clear();
        Vector3 centerPosition = transform.position;
        
        // Generate 4-6 random points around the starting position
        int waypointCount = Random.Range(4, 7);
        
        for (int i = 0; i < waypointCount; i++)
        {
            Vector3 randomDirection = Random.insideUnitSphere * autoPatrolRadius;
            randomDirection.y = 0; // Keep on same Y level
            Vector3 targetPosition = centerPosition + randomDirection;
            
            // Try to find a valid NavMesh position
            if (NavMesh.SamplePosition(targetPosition, out NavMeshHit hit, autoPatrolRadius, NavMesh.AllAreas))
            {
                autoGeneratedWaypoints.Add(hit.position);
            }
            else
            {
                // Fallback to a position closer to center
                Vector3 fallbackPos = centerPosition + (randomDirection.normalized * (autoPatrolRadius * 0.5f));
                if (NavMesh.SamplePosition(fallbackPos, out NavMeshHit fallbackHit, autoPatrolRadius * 0.5f, NavMesh.AllAreas))
                {
                    autoGeneratedWaypoints.Add(fallbackHit.position);
                }
            }
        }

        Debug.Log($"[{name}] Generated {autoGeneratedWaypoints.Count} auto patrol waypoints");
    }

    void Update()
    {
        if (player == null || navMeshAgent == null)
            return;

        // Check for player detection
        bool playerCurrentlyDetected = CheckPlayerDetection();
        
        // Handle state transitions based on detection
        if (playerCurrentlyDetected && !isChasing)
        {
            StartChasing();
        }
        else if (isChasing && !playerCurrentlyDetected)
        {
            // Check if we should stop chasing
            float chaseTime = Time.time - chaseStartTime;
            float distanceToPlayer = Vector3.Distance(transform.position, player.position);
            
            if (chaseTime > chaseTimeout || distanceToPlayer > loseChaseDistance)
            {
                StopChasing();
            }
        }

        // Update behavior based on current state
        switch (currentState)
        {
            case KamatayanAnimationState.Patrolling:
                UpdatePatrolBehavior();
                break;
            case KamatayanAnimationState.Looking:
                UpdateLookingBehavior();
                break;
            case KamatayanAnimationState.Chasing:
                UpdateChaseBehavior();
                break;
            case KamatayanAnimationState.Idle:
                // Do nothing in idle state
                break;
        }
    }

    void UpdatePatrolBehavior()
    {
        // Check if it's time to stop and look around
        if (Time.time - lastLookTime >= lookingInterval && !isLooking)
        {
            StartLooking();
            return;
        }

        // Continue patrolling
        if (!navMeshAgent.pathPending && navMeshAgent.remainingDistance < 0.5f)
        {
            // Reached current waypoint, move to next
            MoveToNextWaypoint();
        }
    }

    void UpdateLookingBehavior()
    {
        // Looking behavior is handled by coroutine
        // This is just a placeholder for any additional looking logic
    }

    void UpdateChaseBehavior()
    {
        if (player == null) return;

        // Update destination to player's current position
        lastKnownPlayerPosition = player.position;
        navMeshAgent.SetDestination(lastKnownPlayerPosition);
        
        // Face the player while chasing
        FaceTarget(player.position);
    }

    bool CheckPlayerDetection()
    {
        if (player == null) return false;

        float distanceToPlayer = Vector3.Distance(transform.position, player.position);
        
        // If already chasing and persistent mode is on
        if (isChasing && persistentChase)
        {
            return distanceToPlayer <= loseChaseDistance;
        }

        // Check if player is within detection radius
        if (distanceToPlayer > detectionRadius)
            return false;

        // If looking, check field of view
        if (isLooking)
        {
            Vector3 directionToPlayer = (player.position - transform.position).normalized;
            float angleToPlayer = Vector3.Angle(transform.forward, directionToPlayer);
            
            if (angleToPlayer > fieldOfViewAngle * 0.5f)
                return false;
        }

        // Check line of sight if required
        if (requireLineOfSight)
        {
            Vector3 origin = transform.position + Vector3.up * 1.6f;
            Vector3 direction = (player.position + Vector3.up * 1.6f) - origin;
            float maxDistance = direction.magnitude;

            if (Physics.Raycast(origin, direction.normalized, out RaycastHit hit, maxDistance, lineOfSightObstructionMask, QueryTriggerInteraction.Ignore))
            {
                // If we hit something that isn't the player, LOS is blocked
                if (hit.transform != player && !hit.transform.IsChildOf(player))
                    return false;
            }
        }

        return true;
    }

    void StartPatrolling()
    {
        SetState(KamatayanAnimationState.Patrolling);
        navMeshAgent.speed = patrolSpeed;
        MoveToNextWaypoint();
    }

    void MoveToNextWaypoint()
    {
        Vector3 targetWaypoint;

        if (patrolWaypoints != null && patrolWaypoints.Length > 0)
        {
            // Use manually set waypoints
            if (useRandomPatrol)
            {
                currentWaypointIndex = Random.Range(0, patrolWaypoints.Length);
            }
            else
            {
                currentWaypointIndex = (currentWaypointIndex + 1) % patrolWaypoints.Length;
            }
            targetWaypoint = patrolWaypoints[currentWaypointIndex].position;
        }
        else if (autoGeneratedWaypoints.Count > 0)
        {
            // Use auto-generated waypoints
            if (useRandomPatrol)
            {
                currentWaypointIndex = Random.Range(0, autoGeneratedWaypoints.Count);
            }
            else
            {
                currentWaypointIndex = (currentWaypointIndex + 1) % autoGeneratedWaypoints.Count;
            }
            targetWaypoint = autoGeneratedWaypoints[currentWaypointIndex];
        }
        else
        {
            Debug.LogWarning($"[{name}] No waypoints available for patrol!");
            return;
        }

        navMeshAgent.SetDestination(targetWaypoint);
        Debug.Log($"[{name}] Moving to waypoint {currentWaypointIndex}: {targetWaypoint}");
    }

    void StartLooking()
    {
        SetState(KamatayanAnimationState.Looking);
        navMeshAgent.isStopped = true;
        isLooking = true;
        lastLookTime = Time.time;
        
        StartCoroutine(LookAroundCoroutine());
    }

    IEnumerator LookAroundCoroutine()
    {
        float lookStartTime = Time.time;
        Vector3 originalForward = transform.forward;
        
        // Look in different directions
        float[] lookAngles = { -90f, 0f, 90f, 180f, 0f }; // Left, forward, right, back, forward again
        
        foreach (float angle in lookAngles)
        {
            if (!isLooking) yield break; // Exit if state changed
            
            Vector3 lookDirection = Quaternion.Euler(0, angle, 0) * originalForward;
            Quaternion targetRotation = Quaternion.LookRotation(lookDirection);
            
            // Smoothly rotate to look direction
            float rotateTime = 0.8f;
            float elapsedTime = 0f;
            Quaternion startRotation = transform.rotation;
            
            while (elapsedTime < rotateTime && isLooking)
            {
                transform.rotation = Quaternion.Slerp(startRotation, targetRotation, elapsedTime / rotateTime);
                elapsedTime += Time.deltaTime;
                yield return null;
            }
            
            // Hold the look for a moment
            yield return new WaitForSeconds(0.5f);
        }
        
        // Finished looking
        if (isLooking) // Only if we weren't interrupted
        {
            StopLooking();
        }
    }

    void StopLooking()
    {
        isLooking = false;
        navMeshAgent.isStopped = false;
        SetState(KamatayanAnimationState.Patrolling);
        
        // Wait a moment before moving to next waypoint
        StartCoroutine(WaitThenContinuePatrol());
    }

    IEnumerator WaitThenContinuePatrol()
    {
        yield return new WaitForSeconds(waitTimeAtWaypoint);
        if (currentState == KamatayanAnimationState.Patrolling)
        {
            MoveToNextWaypoint();
        }
    }

    void StartChasing()
    {
        isChasing = true;
        chaseStartTime = Time.time;
        SetState(KamatayanAnimationState.Chasing);
        navMeshAgent.speed = chaseSpeed;
        navMeshAgent.isStopped = false;
        
        // Stop any looking behavior
        if (isLooking)
        {
            StopCoroutine(LookAroundCoroutine());
            isLooking = false;
        }
        
        Debug.Log($"[{name}] Started chasing player!");
    }

    void StopChasing()
    {
        isChasing = false;
        Debug.Log($"[{name}] Stopped chasing player, returning to patrol");
        StartPatrolling();
    }

    void FaceTarget(Vector3 worldPosition)
    {
        Vector3 toTarget = worldPosition - transform.position;
        toTarget.y = 0f;
        if (toTarget.sqrMagnitude < 0.0001f)
            return;
        Quaternion targetRotation = Quaternion.LookRotation(toTarget.normalized, Vector3.up);
        transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, rotationSpeed * Time.deltaTime);
    }

    void SetState(KamatayanAnimationState newState)
    {
        if (currentState == newState) return;
        
        Debug.Log($"[{name}] State: {currentState} → {newState}");
        currentState = newState;
        
        UpdateAnimationParameters();
    }

    void UpdateAnimationParameters()
    {
        if (animator == null) return;
        
        // Reset all animation parameters
        if (HasParameter(animParamIsIdle))
            animator.SetBool(animParamIsIdle, false);
        if (HasParameter(animParamIsWalking))
            animator.SetBool(animParamIsWalking, false);
        if (HasParameter(animParamIsLooking))
            animator.SetBool(animParamIsLooking, false);
        if (HasParameter(animParamIsChasing))
            animator.SetBool(animParamIsChasing, false);
        
        // Set appropriate parameter based on current state
        switch (currentState)
        {
            case KamatayanAnimationState.Idle:
                if (HasParameter(animParamIsIdle))
                    animator.SetBool(animParamIsIdle, true);
                break;
            case KamatayanAnimationState.Patrolling:
                if (HasParameter(animParamIsWalking))
                    animator.SetBool(animParamIsWalking, true);
                break;
            case KamatayanAnimationState.Looking:
                if (HasParameter(animParamIsLooking))
                    animator.SetBool(animParamIsLooking, true);
                break;
            case KamatayanAnimationState.Chasing:
                if (HasParameter(animParamIsChasing))
                    animator.SetBool(animParamIsChasing, true);
                break;
        }
    }

    bool HasParameter(string paramName)
    {
        if (animator == null || string.IsNullOrEmpty(paramName)) return false;
        
        foreach (var param in animator.parameters)
        {
            if (param.name == paramName) return true;
        }
        return false;
    }

    void OnDrawGizmosSelected()
    {
        // Draw detection radius
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(transform.position, detectionRadius);
        
        // Draw lose chase distance
        Gizmos.color = Color.orange;
        Gizmos.DrawWireSphere(transform.position, loseChaseDistance);
        
        // Draw auto patrol radius
        Gizmos.color = Color.blue;
        Gizmos.DrawWireSphere(transform.position, autoPatrolRadius);
        
        // Draw field of view when looking
        if (isLooking)
        {
            Gizmos.color = Color.red;
            Vector3 leftBoundary = Quaternion.Euler(0, -fieldOfViewAngle * 0.5f, 0) * transform.forward;
            Vector3 rightBoundary = Quaternion.Euler(0, fieldOfViewAngle * 0.5f, 0) * transform.forward;
            
            Gizmos.DrawRay(transform.position, leftBoundary * detectionRadius);
            Gizmos.DrawRay(transform.position, rightBoundary * detectionRadius);
        }
        
        // Draw waypoints
        if (patrolWaypoints != null)
        {
            Gizmos.color = Color.green;
            foreach (Transform waypoint in patrolWaypoints)
            {
                if (waypoint != null)
                {
                    Gizmos.DrawWireSphere(waypoint.position, 1f);
                }
            }
            
            // Draw lines between waypoints
            for (int i = 0; i < patrolWaypoints.Length; i++)
            {
                if (patrolWaypoints[i] != null)
                {
                    Transform nextWaypoint = patrolWaypoints[(i + 1) % patrolWaypoints.Length];
                    if (nextWaypoint != null)
                    {
                        Gizmos.DrawLine(patrolWaypoints[i].position, nextWaypoint.position);
                    }
                }
            }
        }
        
        // Draw auto-generated waypoints
        if (autoGeneratedWaypoints.Count > 0)
        {
            Gizmos.color = Color.cyan;
            foreach (Vector3 waypoint in autoGeneratedWaypoints)
            {
                Gizmos.DrawWireSphere(waypoint, 0.8f);
            }
        }
    }

    // Public methods for external control
    public void SetPatrolWaypoints(Transform[] waypoints)
    {
        patrolWaypoints = waypoints;
    }

    public void AddPatrolWaypoint(Transform waypoint)
    {
        if (patrolWaypoints == null)
        {
            patrolWaypoints = new Transform[] { waypoint };
        }
        else
        {
            Transform[] newWaypoints = new Transform[patrolWaypoints.Length + 1];
            patrolWaypoints.CopyTo(newWaypoints, 0);
            newWaypoints[patrolWaypoints.Length] = waypoint;
            patrolWaypoints = newWaypoints;
        }
    }

    public bool IsPlayerDetected()
    {
        return isPlayerDetected;
    }

    public bool IsChasing()
    {
        return isChasing;
    }

    public KamatayanAnimationState GetCurrentState()
    {
        return currentState;
    }
}
